# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], default='female', max_length=6),
        ),
    ]
