# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20170709_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='curent_country',
            new_name='current_country',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='User_city',
            new_name='user_city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_sate',
            new_name='user_state',
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(),
        ),
    ]
