# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
