# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_association_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='initials',
            field=models.CharField(default='', max_length=25),
        ),
    ]
