# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_profile_association'),
        ('association', '0004_association_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Country'),
        ),
    ]
