# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('association', '0005_association_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='email',
        ),
        migrations.RemoveField(
            model_name='association',
            name='name',
        ),
        migrations.AddField(
            model_name='association',
            name='group',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
