# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('association', '0008_auto_20170712_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='email',
        ),
        migrations.AddField(
            model_name='association',
            name='identifier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
