# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0009_auto_20170712_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
