# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0009_auto_20170712_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='association',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='year_of_creation',
            field=models.DateField(null=True),
        ),
    ]
