# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0010_auto_20170713_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
