# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0011_auto_20170713_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='year_of_creation',
            field=models.DateField(null=True),
        ),
    ]
