# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0012_auto_20170716_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
