# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0014_auto_20170716_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='user',
            new_name='identifier',
        ),
    ]
