# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='replies',
        ),
        migrations.AddField(
            model_name='topic',
            name='reply',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
